CREATE TABLE `shopperBookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tripId` int NOT NULL,
	`customerUserId` int NOT NULL,
	`itemDescription` text NOT NULL,
	`pickupLocationText` text NOT NULL,
	`pickupLocationLat` decimal(10,7),
	`pickupLocationLng` decimal(10,7),
	`pickupStoreName` varchar(255),
	`invoiceImageUrl` text,
	`deliveryFee` decimal(8,2) NOT NULL,
	`shopperPaymentMethod` enum('cash','card') NOT NULL DEFAULT 'cash',
	`shopperPaymentStatus` enum('pending','paid','refunded') NOT NULL DEFAULT 'pending',
	`shopperBookingStatus` enum('pending','accepted','rejected','picked_up','delivered','confirmed','cancelled') NOT NULL DEFAULT 'pending',
	`pickupProofImageUrl` text,
	`deliveryProofImageUrl` text,
	`pickupProofAt` timestamp,
	`deliveryProofAt` timestamp,
	`confirmedByCustomerAt` timestamp,
	`customerNotes` text,
	`driverNotes` text,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopperBookings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shopperDriverSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`driverUserId` int NOT NULL,
	`isActive` boolean NOT NULL DEFAULT false,
	`allowsFood` boolean NOT NULL DEFAULT true,
	`allowsCoffee` boolean NOT NULL DEFAULT true,
	`allowsGroceries` boolean NOT NULL DEFAULT true,
	`allowsPharmacy` boolean NOT NULL DEFAULT true,
	`allowsDocuments` boolean NOT NULL DEFAULT false,
	`allowsElectronics` boolean NOT NULL DEFAULT false,
	`allowsClothes` boolean NOT NULL DEFAULT false,
	`allowsOther` boolean NOT NULL DEFAULT false,
	`customTerms` text,
	`minBookingsToDepart` int NOT NULL DEFAULT 3,
	`maxBookingsPerTrip` int NOT NULL DEFAULT 10,
	`defaultDeliveryFee` decimal(8,2) NOT NULL DEFAULT '15',
	`driverNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopperDriverSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `shopperDriverSettings_driverUserId_unique` UNIQUE(`driverUserId`)
);
--> statement-breakpoint
CREATE TABLE `shopperTrips` (
	`id` int AUTO_INCREMENT NOT NULL,
	`driverUserId` int NOT NULL,
	`fromCityId` int NOT NULL,
	`fromCityName` varchar(100) NOT NULL,
	`toCityId` int NOT NULL,
	`toCityName` varchar(100) NOT NULL,
	`departureTime` timestamp NOT NULL,
	`estimatedArrivalTime` timestamp NOT NULL,
	`shopperTripStatus` enum('upcoming','collecting','departed','arrived','completed','cancelled') NOT NULL DEFAULT 'upcoming',
	`minBookings` int NOT NULL DEFAULT 1,
	`maxBookings` int NOT NULL DEFAULT 10,
	`currentBookings` int NOT NULL DEFAULT 0,
	`deliveryFee` decimal(8,2) NOT NULL DEFAULT '15',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopperTrips_id` PRIMARY KEY(`id`)
);
