CREATE TABLE `placeAnalysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`placeId` varchar(255) NOT NULL,
	`name` varchar(255) NOT NULL,
	`address` text,
	`phone` varchar(50),
	`rating` decimal(3,2),
	`totalRatings` int DEFAULT 0,
	`priceLevel` int,
	`types` text,
	`photoUrl` text,
	`googleMapsUrl` text,
	`lat` decimal(10,7),
	`lng` decimal(10,7),
	`aiSummary` text,
	`aiFamousFor` text,
	`aiTopItems` text,
	`aiTrendingItems` text,
	`aiMenuItems` text,
	`aiAnalyzedAt` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`cityId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `placeAnalysis_id` PRIMARY KEY(`id`),
	CONSTRAINT `placeAnalysis_placeId_unique` UNIQUE(`placeId`)
);
